### ISSUE TITLE
[ERROR] Error raised: 0x00

### ISSUE THREAD

**Issue by benny1611** [DanBrezeanu/R502-fingerprint#2]
Hi,
I'm done implementing the LED functionality, but the problem is that now I get an error every time I run my example `[ERROR] Error raised: 0x00` although everything works just fine. Could you help me out? I also don't know how to make a pull request, never done that before 😅 Do you have a discord server that I can join? Or can you explain a bit how this works?

PS: Your code is really well organized and well commented. I was able to understand the structure in less than 10 minutes (although I have limited experience in C). I'm impressed :)

**Comment by DanBrezeanu** [comment]
Hey! I don't have a discord server. You can check out how to create a pull request for review, [here](https://opensource.com/article/19/7/create-pull-request-github).
