### ISSUE TITLE
[FR] can you help with your code for tasmota?

### ISSUE THREAD

**Issue by ozett** [DanBrezeanu/R502-fingerprint#7]
[someone on tasmota](https://github.com/arendst/Tasmota/pull/9568#issuecomment-1376867630) is using the AS608 driver in tasmota.
which works fine for fingerprinting, but does not control the led.

may your are willing to help a noobie out with some code or assistance?

**Comment by DanBrezeanu** [comment]
@ozett 

Unfortunately, I don't have that device at hand and at the same time I'm not too familliar with the tasmota source code. 

LED issues, fortunately, do not impact the performance and usability of the device too much. 

Feel free to browse this project and open and issues regarding the functionality of this code.

**Comment by ozett** [comment]
thanks for reply.
the folks with the problem tried a lot,
at the end did it without the led-function for reason of stabilty.
https://github.com/arendst/Tasmota/pull/9568#issuecomment-1382928429

i think this is therefore solved
